name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y git zip unzip openjdk-11-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer appdirs colorama>=0.3.3 jinja2 'sh>=1.10,<2.0' build toml packaging setuptools

    - name: Install Android SDK and NDK
      run: |
        # Create Android SDK directory
        mkdir -p ~/Android/Sdk
        
        # Download and install Android Command Line Tools
        cd ~/Android/Sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip
        unzip commandlinetools-linux-6514223_latest.zip
        rm commandlinetools-linux-6514223_latest.zip
        
        # Move to cmdline-tools/latest
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/bin cmdline-tools/latest/
        mv cmdline-tools/lib cmdline-tools/latest/
        mv cmdline-tools/source.properties cmdline-tools/latest/
        
        # Download and install Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        rm android-ndk-r25b-linux.zip
        mv android-ndk-r25b ndk/25.2.9519653

    - name: Build Android App
      run: |
        # Set environment variables
        export ANDROID_HOME=~/Android/Sdk
        export ANDROID_NDK_HOME=~/Android/Sdk/ndk/25.2.9519653
        export PATH=$PATH:~/Android/Sdk/cmdline-tools/latest/bin:~/Android/Sdk/platform-tools
        
        # Build the app
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: mahjong-assist-apk
        path: bin/*.apk
